apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service
    version: v1
spec:
  ports:
  - port: 80
    name: demo
    protocol: TCP #required
    targetPort: 8080
  selector:
      app: demo
      version: v1